#!/usr/bin/env bash
# Gamertown setup — one-time initialization for a fresh clone.
# Installs dependencies (rclone, age), prompts for R2 credentials + age passphrase,
# pulls secrets from R2, and prepares the environment for `docker compose up`.
#
# Usage: tools/setup.sh
set -euo pipefail

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}=== Gamertown Setup ===${NC}"
echo "This will install dependencies and configure your local environment to pull secrets from R2."
echo

# Detect OS
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  OS="linux"
elif [[ "$OSTYPE" == "darwin"* ]]; then
  OS="macos"
elif [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" ]]; then
  OS="windows"
else
  OS="unknown"
fi

# Function to install a tool
install_tool() {
  local cmd=$1
  local pkg=$2

  if command -v "$cmd" &>/dev/null; then
    echo -e "${GREEN}✓ $cmd already installed${NC}"
    return 0
  fi

  echo -e "${YELLOW}Installing $cmd...${NC}"

  case $OS in
    linux)
      if command -v apt &>/dev/null; then
        sudo apt update && sudo apt install -y "$pkg"
      elif command -v yum &>/dev/null; then
        sudo yum install -y "$pkg"
      elif command -v pacman &>/dev/null; then
        sudo pacman -S "$pkg"
      else
        echo -e "${RED}✗ Could not auto-install $pkg on this Linux distribution${NC}"
        echo "  Please install manually: https://rclone.org/install/ or https://github.com/FiloSottile/age/releases"
        return 1
      fi
      ;;
    macos)
      if ! command -v brew &>/dev/null; then
        echo -e "${RED}✗ Homebrew not found${NC}"
        echo "  Install Homebrew first: https://brew.sh"
        return 1
      fi
      brew install "$pkg"
      ;;
    windows)
      echo -e "${YELLOW}On Windows, please install $cmd manually:${NC}"
      if [ "$cmd" = "rclone" ]; then
        echo "  https://rclone.org/install/ (use the Windows installer or Chocolatey)"
      else
        echo "  https://github.com/FiloSottile/age/releases (download the Windows binary)"
      fi
      echo "  Then re-run this script."
      return 1
      ;;
    *)
      echo -e "${RED}✗ Unknown OS: $OSTYPE${NC}"
      echo "  Please install $pkg manually and re-run this script."
      return 1
      ;;
  esac

  if command -v "$cmd" &>/dev/null; then
    echo -e "${GREEN}✓ $cmd installed${NC}"
    return 0
  else
    echo -e "${RED}✗ Failed to install $cmd${NC}"
    return 1
  fi
}

# Install dependencies
install_tool rclone rclone || exit 1
install_tool age age || exit 1
echo

# Prompt for R2 credentials
echo -e "${YELLOW}R2 Credentials${NC}"
read -p "R2 Account ID: " r2_account_id
read -p "R2 Access Key ID: " r2_access_key
read -sp "R2 Secret Access Key: " r2_secret_key
echo
echo

# Set up rclone config (r2 remote)
echo -e "${YELLOW}Configuring rclone...${NC}"
rclone config create r2 s3 \
  provider Cloudflare \
  access_key_id "$r2_access_key" \
  secret_access_key "$r2_secret_key" \
  account_id "$r2_account_id" \
  --non-interactive >/dev/null 2>&1 || true

echo -e "${GREEN}✓ rclone r2 remote configured${NC}"
echo

# Prompt for age passphrase
echo -e "${YELLOW}Age Encryption${NC}"
read -sp "Age passphrase (for decryption): " age_passphrase
echo
echo

# Create secrets directory
secrets_dir="${PWD}/.secrets"
mkdir -p "$secrets_dir"
echo -e "${GREEN}✓ Created secrets directory: $secrets_dir${NC}"
echo

# Pull and decrypt secrets from R2
echo -e "${YELLOW}Pulling secrets from R2...${NC}"
tmp_age="$(mktemp)"
tmp_tar="$(mktemp)"
trap 'rm -f "$tmp_age" "$tmp_tar"' EXIT

rclone copyto "r2:gamertown-backups/secrets/secrets.tar.age" "$tmp_age"
echo -e "${GREEN}✓ Downloaded encrypted secrets${NC}"

# Decrypt using age passphrase
echo "$age_passphrase" | age -d -o "$tmp_tar" "$tmp_age" 2>/dev/null || {
  echo -e "${RED}✗ Failed to decrypt secrets (wrong passphrase?)${NC}"
  exit 1
}
echo -e "${GREEN}✓ Decrypted secrets${NC}"

# Extract to .secrets directory
tar -xzf "$tmp_tar" -C "$secrets_dir" --strip-components=2 || {
  echo -e "${RED}✗ Failed to extract secrets${NC}"
  exit 1
}
echo -e "${GREEN}✓ Extracted secrets${NC}"
echo

# Create .env file with GT_SECRETS_FILE pointing to the local secrets
env_file="${PWD}/.env.local"
cat > "$env_file" << EOF
# Generated by tools/setup.sh
GT_SECRETS_FILE=$secrets_dir/gamertown/secrets.env
EOF

echo -e "${GREEN}✓ Created $env_file${NC}"
echo

# Summary
echo -e "${GREEN}=== Setup Complete ===${NC}"
echo "Secrets have been pulled from R2 and decrypted locally."
echo
echo "Next steps:"
echo "  1. Run: docker compose --env-file .env.local up --build"
echo "  2. Access the app at: https://localhost"
echo "  3. (Accept the self-signed cert warning)"
echo
